# Generated by Django 5.1.1 on 2024-11-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SentiMentAnalysis",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("video_title", models.CharField(max_length=255)),
                ("video_url", models.CharField(max_length=255)),
                ("comment", models.TextField(max_length=500)),
                ("main_result", models.CharField(max_length=100)),
                ("other_result", models.CharField(max_length=100)),
            ],
        ),
    ]
