# Generated by Django 5.1.1 on 2024-11-27 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SentiMentAnalysis",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("video_title", models.CharField(max_length=255)),
                ("video_url", models.CharField(max_length=255)),
                ("comment", models.TextField(max_length=500)),
                ("main_result", models.CharField(max_length=100)),
                ("other_result", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sentiment_analysis.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
