# Generated by Django 5.1.1 on 2025-02-03 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sentiment_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sentimentanalysis",
            options={"verbose_name_plural": "Sentiment Analysis"},
        ),
    ]
