# Generated by Django 5.1.1 on 2025-02-03 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sentiment_analysis", "0002_alter_sentimentanalysis_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
