# Generated by Django 5.1.1 on 2025-02-03 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sentiment_analysis", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sentimentanalysis",
            options={"verbose_name_plural": "Sentiment analysis"},
        ),
    ]
