# Generated by Django 5.1.1 on 2025-02-03 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name_plural": "User accounts"},
        ),
    ]
