# Generated by Django 5.1.1 on 2025-02-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_profilepic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profilePic",
            field=models.ImageField(
                default="/profile-pic/default.png", upload_to="profile-pic"
            ),
        ),
    ]
