# Generated by Django 5.1.1 on 2024-09-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("image_data", models.ImageField(upload_to="images")),
                ("image_name", models.CharField(max_length=120)),
            ],
        ),
    ]
