# Generated by Django 5.1.1 on 2025-02-03 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="images",
            options={"verbose_name_plural": "Images"},
        ),
    ]
