# Generated by Django 5.1.1 on 2025-01-20 19:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("others", "0002_copyrightfooter_navigationlinksfooter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinksFooter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("links_title", models.CharField(max_length=60)),
                ("links_url", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LinksFooterCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category_name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="NavigationLinksFooter",
        ),
        migrations.DeleteModel(
            name="QuickLinksFooter",
        ),
        migrations.AddField(
            model_name="linksfooter",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="others.linksfootercategory",
            ),
        ),
        migrations.AddField(
            model_name="sociallinksfooter",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="others.linksfootercategory",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="titlefooter",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="others.linksfootercategory",
            ),
            preserve_default=False,
        ),
    ]
