# Generated by Django 5.1.1 on 2025-01-21 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("others", "0003_linksfooter_linksfootercategory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linksfooter",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links_footer",
                to="others.linksfootercategory",
            ),
        ),
        migrations.AlterField(
            model_name="sociallinksfooter",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sociallinks_footer",
                to="others.linksfootercategory",
            ),
        ),
        migrations.AlterField(
            model_name="titlefooter",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="title_footer",
                to="others.linksfootercategory",
            ),
        ),
    ]
