# Generated by Django 5.1.1 on 2025-01-21 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("others", "0004_alter_linksfooter_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="titlefooter",
            name="category",
        ),
    ]
