# Generated by Django 5.1.1 on 2025-02-03 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("others", "0006_sociallinksfootercategory_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="copyrightfooter",
            options={"verbose_name_plural": "Copyright footer"},
        ),
        migrations.AlterModelOptions(
            name="linksfooter",
            options={"verbose_name_plural": "Links footer"},
        ),
        migrations.AlterModelOptions(
            name="linksfootercategory",
            options={"verbose_name_plural": "Links footer categories"},
        ),
        migrations.AlterModelOptions(
            name="sociallinksfootercategory",
            options={"verbose_name_plural": "Social Links footer categories"},
        ),
        migrations.AlterModelOptions(
            name="titlefooter",
            options={"verbose_name_plural": "Title footer"},
        ),
        migrations.AlterModelOptions(
            name="topbanner",
            options={"verbose_name_plural": "Top banner"},
        ),
    ]
