# Generated by Django 5.1.1 on 2025-02-03 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("others", "0007_alter_copyrightfooter_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sociallinksfooter",
            options={"verbose_name_plural": "Social links footer"},
        ),
    ]
