# Generated by Django 5.1.1 on 2025-02-16 15:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("others", "0008_alter_sociallinksfooter_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=1000)),
            ],
            options={
                "verbose_name_plural": "About us",
            },
        ),
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=1000)),
            ],
            options={
                "verbose_name_plural": "Privacy Policy",
            },
        ),
    ]
