# Generated by Django 5.1.1 on 2025-02-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("others", "0009_aboutus_privacypolicy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutus",
            name="description",
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="privacypolicy",
            name="description",
            field=models.TextField(max_length=5000),
        ),
    ]
