# Generated by Django 5.1.1 on 2025-01-11 12:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_name", models.CharField(max_length=150)),
                ("product_description", models.TextField(max_length=255)),
                ("product_url", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
