# Generated by Django 5.1.1 on 2025-01-11 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_productlist_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productlist",
            name="user",
        ),
    ]
