# Generated by Django 5.1.1 on 2025-02-03 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_remove_productlist_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productlist",
            options={"verbose_name_plural": "Product list"},
        ),
    ]
