# Generated by Django 5.1.1 on 2025-02-03 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_productlist_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productlist",
            options={},
        ),
    ]
